### ISSUE TITLE
No session ID for selenium

### ISSUE THREAD

**Issue by bczegeny** [nacimgoura/instagram-profilecrawl#15]
I'm getting an error when trying to use selenium scaping. 

I've tried this in ubuntu subsystem and in windows powershell. It worked before but for some reason is not working now. 

I've even tried starting the selenium standalone server manually and it still gives me the same error. 

```
× Timed out waiting for driver server to start.
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'Bens-Desktop.localdomain', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-43-Microsoft', java.version: '1.8.0_151'
Driver info: driver.version: unknown
C:\Users\Benjamin\AppData\Roaming\nvm\v8.5.0\node_modules\instagram-profilecrawl\node_modules\fibers\future.js:313
                                                throw(ex);
                                                ^

Error: A session id is required for this command but wasn't found in the response payload
    at new RuntimeError (C:\Users\Benjamin\AppData\Roaming\nvm\v8.5.0\node_modules\instagram-profilecrawl\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at RequestHandler.createOptions (C:\Users\Benjamin\AppData\Roaming\nvm\v8.5.0\node_modules\instagram-profilecrawl\node_modules\webdriverio\build\lib\utils\RequestHandler.js:121:23)
    at RequestHandler.create (C:\Users\Benjamin\AppData\Roaming\nvm\v8.5.0\node_modules\instagram-profilecrawl\node_modules\webdriverio\build\lib\utils\RequestHandler.js:209:43)
    at Object.url (C:\Users\Benjamin\AppData\Roaming\nvm\v8.5.0\node_modules\instagram-profilecrawl\node_modules\webdriverio\build\lib\protocol\url.js:24:32)
    at Object.exec (C:\Users\Benjamin\AppData\Roaming\nvm\v8.5.0\node_modules\instagram-profilecrawl\node_modules\webdriverio\build\lib\helpers\safeExecute.js:28:24)
    at Object.resolve (C:\Users\Benjamin\AppData\Roaming\nvm\v8.5.0\node_modules\instagram-profilecrawl\node_modules\webdriverio\build\lib\webdriverio.js:191:29)
    at lastPromise.then.resolve.call.depth (C:\Users\Benjamin\AppData\Roaming\nvm\v8.5.0\node_modules\instagram-profilecrawl\node_modules\webdriverio\build\lib\webdriverio.js:486:32)
    at _fulfilled (C:\Users\Benjamin\AppData\Roaming\nvm\v8.5.0\node_modules\instagram-profilecrawl\node_modules\webdriverio\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\Users\Benjamin\AppData\Roaming\nvm\v8.5.0\node_modules\instagram-profilecrawl\node_modules\webdriverio\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\Users\Benjamin\AppData\Roaming\nvm\v8.5.0\node_modules\instagram-profilecrawl\node_modules\webdriverio\node_modules\q\q.js:816:13)```

Is there a specific node version that should be used? Not sure what could have changed to cause this?

**Comment by nacimgoura** [comment]
hello,
I've never had this problem before, so I'll take a look. Thanks for the heads-up.

**Comment by nacimgoura** [comment]
hello, do you still encounter the bug?
